# Generated by Django 4.2.5 on 2023-10-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBalti', '0002_conjunto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='catalogo'),
        ),
    ]
