# Generated by Django 4.2.5 on 2023-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBalti', '0003_alter_conjunto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombacha',
            name='imagen',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='catalogo'),
        ),
        migrations.AddField(
            model_name='dormir',
            name='imagen',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='catalogo'),
        ),
    ]
